# Partie 1 : Listes Python vs tableaux NumPy

**1.Liste Python**


In [8]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
temperatures_liste


[24.5, 25.1, 26.3, 27.0, 25.8]

**2. Tableau NumPy**

In [9]:
import numpy as np
temperatures_numpy = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
temperatures_numpy

array([24.5, 25.1, 26.3, 27. , 25.8])

## Effectuer une multiplication par 2 sur ces deux collections;

Multiplication de la liste Python


In [10]:
temperatures_liste *2  # ici python duplic la liste 2 fois

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

Multiplication de la liste Numpy


In [11]:
temperatures_numpy *2 # Ici Numpy Multiplie chaque element une par une

array([49. , 50.2, 52.6, 54. , 51.6])

### 4. Différence

Avec une liste Python, l'opérateur * 2 répète la liste. Avec un tableau NumPy, il effectue une multiplication élément par élément. NumPy est donc particulièrement adapté aux calculs numériques sur des ensembles de données.

# Partie 2 — Création des données

In [12]:
# 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
temperatures_zero =np.zeros(10) # On cree un tableau de 10 elementen initialisant les valeur par 0
temperatures_zero


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# 2) Créer un tableau contenant 10 valeurs égales à 1.
temperatures_one = np.ones(10)
temperatures_one


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#3) Créer un tableau de 10 valeurs initialisées à 25.

temperature_initial = np.full(10,25)
temperature_initial

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [15]:
#4) Créer une matrice identité de taille 5 × 5.
matrice_identite = np.eye(5)
matrice_identite

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

La matrice identité contient des 1 sur la diagonale principale et des 0 ailleurs.

In [16]:
#5) Créer les 24 heures (de 0 à 23) de mesure d’une journée
heure_journee = np.arange(24)
heure_journee

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
# 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
temperatures_regulieres = np.linspace(20, 30, 10)
temperatures_regulieres


array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

#np.linspace() génère ici 10 valeurs régulièrement espacées entre 20 et 30.


In [18]:
# 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

np.random.seed(42) # le mdoule pour generer des nombre aleatoire

temperatures_aleatoires = np.random.uniform(20, 35, 100)
temperatures_aleatoires

array([25.61810178, 34.2607146 , 30.97990913, 28.97987726, 22.34027961,
       22.33991781, 20.87125418, 32.99264219, 29.01672518, 30.62108867,
       20.30876741, 34.54864778, 32.48663961, 23.18508666, 22.72737451,
       22.75106765, 24.56363364, 27.87134647, 26.47917528, 24.3684371 ,
       29.17779342, 22.09240791, 24.38216973, 25.49542765, 26.84104976,
       31.77763942, 22.99510673, 27.71351658, 28.88621853, 20.69675619,
       29.11317278, 22.55786186, 20.97577389, 34.23328306, 34.4844805 ,
       32.12596022, 24.56920654, 21.46508171, 30.2634954 , 26.60228741,
       21.83057352, 27.42765365, 20.51582782, 33.63980603, 23.88169972,
       29.93783427, 24.67566614, 27.80102032, 28.20065419, 22.77281683,
       34.54376942, 31.62699235, 34.09248412, 33.42241026, 28.96849968,
       33.82811353, 21.32738753, 22.93974294, 20.67840933, 24.87995496,
       25.83015935, 24.07023548, 32.43106264, 25.3512999 , 24.21401765,
       28.14044125, 22.11386337, 32.03295471, 21.11825966, 34.80

ici :
20 → température minimale
35 → limite supérieure
100 → nombre de mesures
seed(42) → permet d'obtenir les mêmes valeurs à chaque exécution

 À retenir :

Fonction	Utilisation

np.zeros()	Remplir de 0

np.ones()	Remplir de 1

np.full()	Remplir d'une valeur choisie

np.eye()	Matrice identité

np.arange()	Suite avec un pas

np.linspace()	Valeurs régulièrement espacées

np.random	Génération aléatoire

# Partie 3 — Exploration des tableaux
**1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :**


In [19]:
np.random.seed(42)

temperatures_journee = np.random.uniform(20, 35, 24)
temperatures_journee

array([25.61810178, 34.2607146 , 30.97990913, 28.97987726, 22.34027961,
       22.33991781, 20.87125418, 32.99264219, 29.01672518, 30.62108867,
       20.30876741, 34.54864778, 32.48663961, 23.18508666, 22.72737451,
       22.75106765, 24.56363364, 27.87134647, 26.47917528, 24.3684371 ,
       29.17779342, 22.09240791, 24.38216973, 25.49542765])

## 2) Déterminer les propriétés suivantes du tableau

**a) nombre de dimensions ;**


In [20]:
temperatures_journee.ndim

1

b) Nombre de valeurs


In [21]:
temperatures_journee.size

24

In [22]:
temperatures_journee.dtype

dtype('float64')

**À retenir**
ndim  → combien de dimensions ?

size  → combien de valeurs ?

dtype → quel type de données ?

shape → quelle forme ?

En NumPy, l'index commence à **0**.

`[0]` récupère donc la température de **0h**.

In [23]:
premiere_mesure = temperatures_journee[1]
premiere_mesure

np.float64(34.260714596148745)

**2.Derniere mesure**

In [24]:
derniere_mesure = temperatures_journee[-1]
derniere_mesure

np.float64(25.495427649405375)

[-1] permet d'accéder directement au dernier élément.

**3) la température de 8h ;**  

In [25]:
temperature_8h = temperatures_journee[8]
temperature_8h

np.float64(29.01672517614813)

4) les températures de 8h à 12h ;

 En slicing, la borne de fin est exclue.

In [27]:
temperatures_8h_12h = temperatures_journee[8:13]
temperatures_8h_12h

array([29.01672518, 30.62108867, 20.30876741, 34.54864778, 32.48663961])


**5) les températures des 6 premières heures ;**


In [29]:
six_premier_heure = temperatures_journee[:6]
six_premier_heure

array([25.61810178, 34.2607146 , 30.97990913, 28.97987726, 22.34027961,
       22.33991781])

6) les heures de paires

on utlise un pas de 2

In [30]:
temperatures_heures_paires = temperatures_journee[::2]
temperatures_heures_paires

array([25.61810178, 30.97990913, 22.34027961, 20.87125418, 29.01672518,
       20.30876741, 32.48663961, 22.72737451, 24.56363364, 26.47917528,
       29.17779342, 24.38216973])

**Le slicing :**

**Syntaxe**

[debut:fin:pas]


[::2]

signifie : commencer au début, aller jusqu'à la fin, et prendre un élément sur deux.

On récupère donc les mesures de :

# Partie 5 — Filtrage booléen

Le filtrage booléen permet de sélectionner uniquement les valeurs d'un tableau qui respectent une condition.

On utilise une condition qui produit un tableau de True et False.


**1) Afficher les températures supérieures à 30 °C**


In [31]:
# Crée une condition booléenne :
# True pour les températures > 30, False sinon
condition = temperatures_journee > 30

# Utilise cette condition pour filtrer le tableau
temperatures_sup_30 = temperatures_journee[condition]

temperatures_sup_30

array([34.2607146 , 30.97990913, 32.99264219, 30.62108867, 34.54864778,
       32.48663961])

2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C


In [33]:
# Vérifie les deux conditions :
# température >= 20 ET température <= 30
condition_normale = (
    (temperatures_journee >= 20)
    & (temperatures_journee <= 30)
)

# On Sélectionne uniquement les températures normales
temperatures_normales = temperatures_journee[condition_normale]

temperatures_normales

array([25.61810178, 28.97987726, 22.34027961, 22.33991781, 20.87125418,
       29.01672518, 20.30876741, 23.18508666, 22.72737451, 22.75106765,
       24.56363364, 27.87134647, 26.47917528, 24.3684371 , 29.17779342,
       22.09240791, 24.38216973, 25.49542765])

**Opérateurs utilisés**

>= : supérieur ou égal.

<= : inférieur ou égal.

& : ET logique élément par élément.

⚠️ Avec NumPy, pour combiner plusieurs conditions, on utilise & et on met chaque condition entre parenthèses.


**3. Détection des anomalies**

Une température supérieure à 35 °C est considérée comme anormale.

In [35]:
# Utilise le tableau booléen pour récupérer les valeurs
# Crée un tableau booléen indiquant les anomalies
anomalies = temperatures_journee > 35

anomalies

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

Ici, anomalies contient uniquement des True et False comme montre le resultat

Cela signifie que les mesures correspondant aux positions 2 et 4 sont anormales.

On peut ensuite récupérer directement les températures concernées :

In [36]:
# Utilise le tableau booléen pour récupérer les valeurs anormales
temperatures_anormales = temperatures_journee[anomalies]

temperatures_anormales

array([], dtype=float64)

**4. Compter les anomalies**

In [37]:
# np.sum() additionne les valeurs True/False.
# True vaut 1 et False vaut 0.
nombre_anomalies = np.sum(anomalies)

nombre_anomalies

np.int64(0)

# Partie 6 – Manipulation des dimensions

On passe maintenant aux tableaux 2D.

Jusqu'ici, temperatures_journee représentait les 24 mesures d'un seul capteur.

Maintenant, on considère 5 capteurs mesurant la température pendant 24 heures.

On va donc créer une matrice :

## 1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée


In [38]:
# Génère les températures de 5 capteurs pendant 24 heures
temperatures_capteurs = np.random.uniform(
    20,
    35,
    size=(5, 24)
)

temperatures_capteurs

array([[26.84104976, 31.77763942, 22.99510673, 27.71351658, 28.88621853,
        20.69675619, 29.11317278, 22.55786186, 20.97577389, 34.23328306,
        34.4844805 , 32.12596022, 24.56920654, 21.46508171, 30.2634954 ,
        26.60228741, 21.83057352, 27.42765365, 20.51582782, 33.63980603,
        23.88169972, 29.93783427, 24.67566614, 27.80102032],
       [28.20065419, 22.77281683, 34.54376942, 31.62699235, 34.09248412,
        33.42241026, 28.96849968, 33.82811353, 21.32738753, 22.93974294,
        20.67840933, 24.87995496, 25.83015935, 24.07023548, 32.43106264,
        25.3512999 , 24.21401765, 28.14044125, 22.11386337, 32.03295471,
        21.11825966, 34.80330405, 31.58367154, 22.98073522],
       [20.08283176, 32.23192143, 30.60286016, 30.93510752, 31.5690552 ,
        21.11066978, 25.37698593, 21.73803589, 32.94655139, 29.3494719 ,
        24.96347037, 20.95337525, 24.66473483, 24.87774983, 30.94409268,
        29.56336207, 33.30819114, 27.08322388, 21.79391369, 30.69867181,
  

20 → température minimale

35 → température maximale

size=(5, 24) → 5 capteurs × 24 heures

On obtient donc une matrice de forme :

In [41]:
temperatures_capteurs.shape

(5, 24)

**2.Transformer la matrice en tableau 1D**

In [42]:
# Transforme la matrice 5 × 24 en un tableau à une seule dimension
temperatures_1d = temperatures_capteurs.flatten()

temperatures_1d

array([26.84104976, 31.77763942, 22.99510673, 27.71351658, 28.88621853,
       20.69675619, 29.11317278, 22.55786186, 20.97577389, 34.23328306,
       34.4844805 , 32.12596022, 24.56920654, 21.46508171, 30.2634954 ,
       26.60228741, 21.83057352, 27.42765365, 20.51582782, 33.63980603,
       23.88169972, 29.93783427, 24.67566614, 27.80102032, 28.20065419,
       22.77281683, 34.54376942, 31.62699235, 34.09248412, 33.42241026,
       28.96849968, 33.82811353, 21.32738753, 22.93974294, 20.67840933,
       24.87995496, 25.83015935, 24.07023548, 32.43106264, 25.3512999 ,
       24.21401765, 28.14044125, 22.11386337, 32.03295471, 21.11825966,
       34.80330405, 31.58367154, 22.98073522, 20.08283176, 32.23192143,
       30.60286016, 30.93510752, 31.5690552 , 21.11066978, 25.37698593,
       21.73803589, 32.94655139, 29.3494719 , 24.96347037, 20.95337525,
       24.66473483, 24.87774983, 30.94409268, 29.56336207, 33.30819114,
       27.08322388, 21.79391369, 30.69867181, 31.41177573, 28.41

On utilise flatten pour créer une copie du tableau sous forme unidimensionnelle.

**3) Déterminer la transposée de la matrice**

In [43]:
# Inverse les lignes et les colonnes
temperatures_transposees = temperatures_capteurs.T
# le T est labrege de "Transpose"

temperatures_transposees

array([[26.84104976, 28.20065419, 20.08283176, 27.84099244, 32.11160233],
       [31.77763942, 22.77281683, 32.23192143, 26.41311528, 33.4413695 ],
       [22.99510673, 34.54376942, 30.60286016, 20.3812869 , 24.77005212],
       [27.71351658, 31.62699235, 30.93510752, 21.6183714 , 21.65077887],
       [28.88621853, 34.09248412, 31.5690552 , 20.47143779, 23.41902744],
       [20.69675619, 33.42241026, 21.11066978, 29.54615617, 26.40661683],
       [29.11317278, 28.96849968, 25.37698593, 24.71533972, 32.27022149],
       [22.55786186, 33.82811353, 21.73803589, 27.62856037, 32.91095875],
       [20.97577389, 21.32738753, 32.94655139, 33.61349711, 20.10428196],
       [34.23328306, 22.93974294, 29.3494719 , 23.73938344, 27.66120954],
       [34.4844805 , 20.67840933, 24.96347037, 26.15574385, 26.26116505],
       [32.12596022, 24.87995496, 20.95337525, 31.33326708, 23.33161716],
       [24.56920654, 25.83015935, 24.66473483, 23.43197248, 21.79798051],
       [21.46508171, 24.07023548, 24.8


Les lignes deviennent des colonnes et les colonnes deviennent des lignes.

**4. Mesures du capteur**


In [44]:
# Sélectionne la première ligne : capteur 1
capteur_1 = temperatures_capteurs[0]

capteur_1

array([26.84104976, 31.77763942, 22.99510673, 27.71351658, 28.88621853,
       20.69675619, 29.11317278, 22.55786186, 20.97577389, 34.23328306,
       34.4844805 , 32.12596022, 24.56920654, 21.46508171, 30.2634954 ,
       26.60228741, 21.83057352, 27.42765365, 20.51582782, 33.63980603,
       23.88169972, 29.93783427, 24.67566614, 27.80102032])


**5) Extraire toutes les mesures du capteur 5 ;**


In [45]:
# Sélectionne la cinquième ligne : capteur 5
capteur_5 = temperatures_capteurs[4]

capteur_5

array([32.11160233, 33.4413695 , 24.77005212, 21.65077887, 23.41902744,
       26.40661683, 32.27022149, 32.91095875, 20.10428196, 27.66120954,
       26.26116505, 23.33161716, 21.79798051, 25.06422757, 34.14364556,
       24.84804398, 27.78185933, 30.54528438, 25.45444404, 34.57673124,
       34.43670942, 23.77673444, 27.45872759, 24.51317465])

**6) Extraire les mesures de tous les capteurs à 10h ;**


In [46]:
# Sélectionne toutes les lignes et la colonne correspondant à 10h
temperatures_10h = temperatures_capteurs[:, 10]

temperatures_10h

array([34.4844805 , 20.67840933, 24.96347037, 26.15574385, 26.26116505])

**7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.**


In [48]:
# Capteurs 2, 3 et 4
# Heures 8, 9, 10, 11 et 12
mesures_selectionnees = temperatures_capteurs[1:4, 8:13]

mesures_selectionnees

array([[21.32738753, 22.93974294, 20.67840933, 24.87995496, 25.83015935],
       [32.94655139, 29.3494719 , 24.96347037, 20.95337525, 24.66473483],
       [33.61349711, 23.73938344, 26.15574385, 31.33326708, 23.43197248]])

À retenir
Pour une matrice NumPy :

tableau[ligne, colonne]

et avec le slicing :

tableau[lignes, colonnes]

C'est essentiel pour manipuler les données sous forme de matrices, ce qui est très fréquent en Data Science et Machine Learning.

**Partie 7 — Concaténation**

**1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs
durant une journée**

In [52]:
# Génère les températures de 3 capteurs pendant 24 heures
temperatures_batiment2 = np.random.uniform(
    20,
    35,
    size=(3, 24)
)

temperatures_batiment2

array([[24.27260742, 20.55330421, 29.14346501, 27.54018535, 20.77218127,
        24.17969696, 33.62398829, 23.59342836, 22.17342308, 27.3417914 ,
        34.78475681, 23.63082907, 30.08203321, 31.42429423, 23.56456316,
        30.92324523, 25.51674699, 29.48458746, 29.50294566, 28.03662026,
        21.35434655, 32.52953743, 24.81170097, 22.79777766],
       [20.61162712, 28.86339415, 30.16346543, 20.24881743, 27.68139587,
        23.39743663, 29.67759186, 22.61549644, 30.36406607, 25.80103019,
        34.05094983, 22.06281416, 25.11599527, 21.70210282, 33.87040427,
        33.1600903 , 23.86912442, 29.89976069, 32.258333  , 28.32801217,
        27.94475868, 23.62778436, 21.39654152, 33.45823637],
       [33.50627086, 29.49652186, 25.08544687, 25.23814362, 30.88933518,
        33.4566539 , 33.30629636, 31.69813319, 29.63047469, 21.26209947,
        22.42443071, 33.47831283, 29.09643589, 20.13795577, 21.52207314,
        29.95252654, 20.07592376, 22.41212077, 28.23100684, 30.37842797,
  


**Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par
les 8 capteurs durant une journée**

In [53]:
# Génère les températures de 3 capteurs pendant 24 heures
temperatures_batiment2 = np.random.uniform(
    20,
    35,
    size=(3, 24)
)

temperatures_batiment2

array([[24.88099547, 31.19737108, 29.74449349, 32.73835116, 29.86419338,
        28.52462905, 21.40512152, 25.51573705, 23.97803552, 23.65984465,
        34.59515832, 25.89646587, 33.38069833, 29.46707939, 31.92216955,
        27.5395564 , 28.65355827, 27.38776541, 22.92864482, 30.83678173,
        24.21158544, 20.3647395 , 29.68208444, 22.65666019],
       [34.10687877, 34.30892866, 33.72296585, 25.5523805 , 20.23184925,
        33.92477844, 26.42276222, 34.49982229, 34.45429966, 32.79514183,
        24.41673338, 25.77646593, 32.76705007, 24.75383008, 22.5423912 ,
        28.35201894, 34.04232161, 30.44044695, 28.55091755, 21.45764741,
        29.2251084 , 34.85080775, 22.10126023, 27.77494479],
       [33.16059608, 31.11152927, 30.45523611, 30.53726126, 25.39236727,
        24.40387766, 32.14041733, 32.15170092, 33.00608478, 33.69860829,
        27.67013598, 27.52274442, 31.97442768, 29.74945896, 30.52950316,
        31.93689004, 33.35008013, 25.06992735, 25.63374429, 21.4097291 ,
  

On a donc

In [57]:
temperatures_capteurs.shape
# (5, 24)

(5, 24)

In [59]:
temperatures_batiment2.shape

# (3, 24)



(3, 24)

**Fusionner les 8 capteurs**
Méthode 1 — np.concatenate()

np.concatenate() permet de joindre plusieurs tableaux NumPy selon un axe donné.

In [60]:
# Fusionne les lignes des deux bâtiments
temperatures_8_capteurs = np.concatenate(
    (temperatures_capteurs, temperatures_batiment2),
    axis=0
)

temperatures_8_capteurs

array([[26.84104976, 31.77763942, 22.99510673, 27.71351658, 28.88621853,
        20.69675619, 29.11317278, 22.55786186, 20.97577389, 34.23328306,
        34.4844805 , 32.12596022, 24.56920654, 21.46508171, 30.2634954 ,
        26.60228741, 21.83057352, 27.42765365, 20.51582782, 33.63980603,
        23.88169972, 29.93783427, 24.67566614, 27.80102032],
       [28.20065419, 22.77281683, 34.54376942, 31.62699235, 34.09248412,
        33.42241026, 28.96849968, 33.82811353, 21.32738753, 22.93974294,
        20.67840933, 24.87995496, 25.83015935, 24.07023548, 32.43106264,
        25.3512999 , 24.21401765, 28.14044125, 22.11386337, 32.03295471,
        21.11825966, 34.80330405, 31.58367154, 22.98073522],
       [20.08283176, 32.23192143, 30.60286016, 30.93510752, 31.5690552 ,
        21.11066978, 25.37698593, 21.73803589, 32.94655139, 29.3494719 ,
        24.96347037, 20.95337525, 24.66473483, 24.87774983, 30.94409268,
        29.56336207, 33.30819114, 27.08322388, 21.79391369, 30.69867181,
  

In [61]:
temperatures_8_capteurs.shape

(8, 24)

**Méthode 2 — np.vstack()**

vstack() signifie vertical stack : empiler les tableaux verticalement.

In [62]:
# Empile verticalement les données des deux bâtiments
temperatures_8_capteurs_v2 = np.vstack(
    (temperatures_capteurs, temperatures_batiment2)
)

temperatures_8_capteurs_v2

array([[26.84104976, 31.77763942, 22.99510673, 27.71351658, 28.88621853,
        20.69675619, 29.11317278, 22.55786186, 20.97577389, 34.23328306,
        34.4844805 , 32.12596022, 24.56920654, 21.46508171, 30.2634954 ,
        26.60228741, 21.83057352, 27.42765365, 20.51582782, 33.63980603,
        23.88169972, 29.93783427, 24.67566614, 27.80102032],
       [28.20065419, 22.77281683, 34.54376942, 31.62699235, 34.09248412,
        33.42241026, 28.96849968, 33.82811353, 21.32738753, 22.93974294,
        20.67840933, 24.87995496, 25.83015935, 24.07023548, 32.43106264,
        25.3512999 , 24.21401765, 28.14044125, 22.11386337, 32.03295471,
        21.11825966, 34.80330405, 31.58367154, 22.98073522],
       [20.08283176, 32.23192143, 30.60286016, 30.93510752, 31.5690552 ,
        21.11066978, 25.37698593, 21.73803589, 32.94655139, 29.3494719 ,
        24.96347037, 20.95337525, 24.66473483, 24.87774983, 30.94409268,
        29.56336207, 33.30819114, 27.08322388, 21.79391369, 30.69867181,
  

Verifications

In [63]:
temperatures_8_capteurs_v2.shape

(8, 24)

# Partie 8 : Calcul scientifique

Ici, on passe de la manipulation des données à leur analyse numérique.

On travaille toujours avec :

temperatures_capteurs

qui contient les températures de 5 capteurs pendant 24 heures


****1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la****

**Statistiques de base**
🔹 Minimum — np.min()

Permet de trouver la plus petite valeur du tableau.


In [64]:
temperature_min = np.min(temperatures_capteurs)

temperature_min

np.float64(20.082831756854034)

Temperature Max

In [66]:
temperature_max = np.max(temperatures_capteurs)

temperature_max

np.float64(34.803304049007764)


**Somme — np.sum()**

Additionne toutes les valeurs.


In [67]:
total_temperatures = np.sum(temperatures_capteurs)

total_temperatures

np.float64(3279.076127630094)

⭐ axis : notion importante pour le ML

C'est ici qu'il faut vraiment comprendre axis.

Notre tableau possède :

5 lignes × 24 colonnes
             heures →
         0   1   2   ... 23
       ┌─────────────────────
Capteur 1
Capteur 2
Capteur 3
Capteur 4
Capteur 5
axis=0

On effectue le calcul verticalement, donc on combine les valeurs des différents capteurs.

Par exemple :

moyenne_par_heure = np.mean(temperatures_capteurs, axis=0)

Résultat :

24 valeurs

➡️ Une moyenne pour chaque heure, calculée à partir des 5 capteurs.

axis=1

On effectue le calcul horizontalement, donc on combine les 24 heures.

moyenne_par_capteur = np.mean(temperatures_capteurs, axis=1)

Résultat :

5 valeurs

➡️ Une moyenne pour chaque capteur sur toute la journée.

🧠 À retenir
axis=0 → on réduit les lignes → résultat par colonne
axis=1 → on réduit les colonnes → résultat par ligne

C'est une notion très importante avec NumPy, Pandas et le Machine Learning.

**Médiane — np.median()**

La médiane correspond à la valeur centrale lorsque les données sont classées.

In [68]:
temperature_mediane = np.median(temperatures_capteurs)

temperature_mediane

np.float64(27.417293798567457)

**Pourquoi utiliser la médiane ?**

Elle est généralement moins influencée par les valeurs extrêmes que la moyenne.

Exemple :

20  21  22  23  80

La moyenne est fortement influencée par 80.

**La médiane reste :**

22


**Variance — np.var()**

La variance mesure à quel point les valeurs sont dispersées autour de la moyenne.


In [69]:
temperature_variance = np.var(temperatures_capteurs)

temperature_variance

np.float64(19.94001432298644)

**Une variance faible :**

valeurs proches de la moyenne

**Une variance élevée :**

valeurs très dispersées

**Écart-type — np.std()**

L'écart-type mesure également la dispersion des données.


In [70]:
temperature_ecart_type = np.std(temperatures_capteurs)

temperature_ecart_type


np.float64(4.4654243161189555)

La différence importante :

Variance       → unité au carré
Écart-type     → même unité que les données

Pour nos températures, l'écart-type est donc exprimé en °C.

**2. Standardisation**

La standardisation transforme les données afin qu'elles aient généralement :

moyenne ≈ 0
écart-type ≈ 1

La formule est :

z = (x - moyenne) / écart-type

En NumPy :

In [71]:
moyenne = np.mean(temperatures_capteurs)
ecart_type = np.std(temperatures_capteurs)

temperatures_standardisees = (
    (temperatures_capteurs - moyenne)
    / ecart_type
)

temperatures_standardisees

array([[-0.10851928,  0.99699485, -0.96979085,  0.08686345,  0.34948171,
        -1.4844901 ,  0.4003065 , -1.06770873, -1.42200607,  1.54691876,
         1.60317264,  1.07499881, -0.6172824 , -1.31242907,  0.65791307,
        -0.16198841, -1.23057978,  0.02284649, -1.52500773,  1.41401381,
        -0.77124466,  0.58498357, -0.59344153,  0.10645929],
       [ 0.19595446, -1.0195711 ,  1.61644997,  0.96325851,  1.51538784,
         1.36532957,  0.36790799,  1.45618393, -1.3432647 , -0.98218918,
        -1.48859875, -0.54769251, -0.334901  , -0.72902342,  1.14332432,
        -0.44213816, -0.69682443,  0.1824702 , -1.16713903,  1.05417089,
        -1.3900974 ,  1.67457091,  0.95355712, -0.97300925],
       [-1.62197411,  1.09872807,  0.73391139,  0.80831582,  0.95028389,
        -1.3917971 , -0.43638596, -1.25130292,  1.25876436,  0.45322401,
        -0.52898982, -1.42702209, -0.59588952, -0.54818633,  0.81032798,
         0.50112319,  1.33975101, -0.05428611, -1.23878949,  0.75536773,
  

Verifications

**Verifications**

In [72]:
np.mean(temperatures_standardisees)

np.float64(-3.9968028886505636e-16)

In [73]:
np.std(temperatures_standardisees)

np.float64(1.0)

**Pourquoi standardiser ?**

En Machine Learning, certaines variables peuvent avoir des échelles très différentes.

**Par exemple :**

Température       → 20 à 35
Pression          → 950 à 1050
Consommation      → 0 à 10000

Sans transformation, certaines variables peuvent avoir une influence disproportionnée dans certains algorithmes.

La standardisation permet de mettre les variables sur une échelle comparable.

35. Normalisation Min-Max

La normalisation Min-Max transforme les valeurs généralement dans l'intervalle :

[0, 1]

Formule :

(x - minimum) / (maximum - minimum)

En NumPy :

In [74]:
temperature_min = np.min(temperatures_capteurs)
temperature_max = np.max(temperatures_capteurs)

temperatures_normalisees = (
    (temperatures_capteurs - temperature_min)
    / (temperature_max - temperature_min)
)

temperatures_normalisees

array([[0.45910334, 0.79445873, 0.19783842, 0.51837228, 0.59803698,
        0.04170548, 0.61345457, 0.16813524, 0.06065988, 0.96127699,
        0.97834149, 0.81812106, 0.30477112, 0.09389984, 0.69159898,
        0.44288359, 0.11872865, 0.49895287, 0.02941455, 0.92096055,
        0.25806699, 0.66947597, 0.31200319, 0.52431664],
       [0.55146481, 0.18273769, 0.98236914, 0.78422488, 0.95171215,
        0.90619229, 0.60362655, 0.93375277, 0.08454591, 0.19407741,
        0.04045914, 0.32588107, 0.39043092, 0.27087471, 0.83884747,
        0.35790075, 0.28064221, 0.54737439, 0.13797326, 0.81180296,
        0.07033931, 1.        , 0.78128198, 0.19686213],
       [0.        , 0.82531929, 0.71465291, 0.73722334, 0.78028906,
        0.06982371, 0.35964567, 0.11244233, 0.87386596, 0.62950699,
        0.33155449, 0.05913829, 0.3112606 , 0.32573127, 0.73783373,
        0.6440371 , 0.89843309, 0.47555486, 0.11623825, 0.72116165,
        0.76960465, 0.56630834, 0.77998013, 0.49754533],
       [0.527

Verifications

In [75]:
np.min(temperatures_normalisees)

np.float64(0.0)

In [76]:
np.max(temperatures_normalisees)

np.float64(1.0)

**Standardisation vs normalisation**

Standardisation :

moyenne ≈ 0
écart-type ≈ 1

Min-Max :

minimum = 0
maximum = 1

Ce sont deux techniques différentes de mise à l'échelle des données.

**4. Conversion Celsius → Fahrenheit**

La formule est :

°F = °C × 9/5 + 32

NumPy permet d'appliquer directement cette opération à tout le tableau :

In [77]:
temperatures_fahrenheit = (
    temperatures_capteurs * 9 / 5 + 32
)

temperatures_fahrenheit

array([[80.31388957, 89.19975096, 73.39119212, 81.88432984, 83.99519336,
        69.25416114, 84.403711  , 72.60415134, 69.75639301, 93.61990951,
        94.07206489, 89.8267284 , 76.22457177, 70.63714708, 86.47429172,
        79.88411733, 71.29503234, 81.36977657, 68.92849007, 92.55165086,
        74.9870595 , 85.88810168, 76.41619905, 82.04183657],
       [82.76117754, 72.9910703 , 94.17878495, 88.92858623, 93.36647142,
        92.16033846, 84.14329943, 92.89060435, 70.38929756, 73.29153729,
        69.2211368 , 76.78391893, 78.49428682, 75.32642386, 90.37591275,
        77.63233982, 75.58523176, 82.65279425, 71.80495407, 89.65931848,
        70.01286738, 94.64594729, 88.85060877, 73.3653234 ],
       [68.14909716, 90.01745857, 87.08514828, 87.68319354, 88.82429936,
        69.9992056 , 77.67857467, 71.12846461, 91.3037925 , 84.82904942,
        76.93424667, 69.71607546, 76.39652269, 76.77994969, 87.69936682,
        85.21405173, 91.95474405, 80.74980298, 71.22904464, 87.25760926,
  

**Pas besoin de faire une boucle for.**

C'est justement l'un des grands avantages de NumPy : les opérations vectorisées.

 Ce qu'il faut retenir de cette partie
Fonction	Rôle

np.min()	valeur minimale

np.max()	valeur maximale

np.sum()	somme

np.mean()	moyenne

np.median()	médiane

np.var()	variance

np.std()	écart-type

Et surtout :

axis=0

➡ calcul par colonne

axis=1

➡ calcul par ligne

Puis :

Standardisation → moyenne 0, écart-type 1.

Min-Max → valeurs entre 0 et 1.

Vectorisation → appliquer une opération à tout un tableau sans écrire explicitement une boucle.


**Partie 9 — Broadcasting**

Le broadcasting est une fonctionnalité de NumPy qui permet d'effectuer une opération entre des tableaux de dimensions différentes, lorsque leurs dimensions sont compatibles.

Ici, on va appliquer une correction différente à chacun des 3 capteurs, sans écrire de boucle.

**1. Créer temperatures_3x3**

On veut représenter :

3 capteurs
3 heures : 10h, 11h et 12h

Donc notre tableau aura la forme :

In [78]:
# Générateur aléatoire reproductible
rng = np.random.default_rng(42)

# Températures de 3 capteurs entre 20 °C et 35 °C
temperatures_3x3 = rng.uniform(
    20,
    35,
    size=(3, 3)
)

temperatures_3x3

array([[31.60934073, 26.5831766 , 32.8789688 ],
       [30.46052044, 21.41266022, 34.63433527],
       [31.41709553, 31.79096458, 21.92170449]])

2. Créer les corrections

L'énoncé nous donne :

In [79]:
correction = np.array([1, -0.5, 0.2])

**3. Appliquer le Broadcasting**

In [80]:
mesures_corrigees = temperatures_3x3 + correction

mesures_corrigees

array([[32.60934073, 26.0831766 , 33.0789688 ],
       [31.46052044, 20.91266022, 34.83433527],
       [32.41709553, 31.29096458, 22.12170449]])

**Pourquoi parle-t-on de Broadcasting ?**

Parce que NumPy étend conceptuellement le petit tableau correction pour pouvoir effectuer l'opération avec le tableau 3 × 3.

Il n'est pas nécessaire de créer manuellement :